name: wsl-build-upload

on:
  push:
    branches:
      - main
      - wsl-build-action

jobs:
  build-push-wsl-image:
    runs-on: windows-latest
    steps:
      - uses: Vampire/setup-wsl@v6
        with:
          distribution: Ubuntu-22.04
          wsl-version: 2

      - shell: wsl-bash {0}
        run: |
          export NEXTFLOW_VER="25.10.3"

          sudo apt update
          sudo apt upgrade -y
          sudo apt install -y openjdk-21-jre-headless docker.io

          useradd user
          echo "user:user" | chpasswd
          usermod -aG docker user

          wget --directory-prefix /usr/local/bin/ https://github.com/nextflow-io/nextflow/releases/download/v${NEXTFLOW_VER}/nextflow

          chmod 755 /usr/local/bin/nextflow

          mkdir -p /home/user/.nextflow
          chmod 755 /usr/local/bin/nextflow

          nextflow info

          chown -R user:user /home/user/.nextflow

          usermod -aG docker user

          echo "export PATH=/usr/local/bin:\$PATH" >> /home/user/.bashrc

          sed -i 's/127.0.1.1.*/127.0.1.1 glacier/' /etc/hosts

          systemctl enable docker

      - uses: Vampire/setup-wsl@v6
        with:
          wsl-version: 2
          distribution: Ubuntu-22.04
          wsl-conf: |
            [boot]
            systemd=true

            [user]
            default=user

      - name: Export WSL image
        shell: powershell
        run: |
          wsl.exe --list --verbose
          wsl.exe --export Ubuntu glacier.tar

      - uses: actions/checkout@master
      - uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: "loman-labz-public-datasets"
          endpoint: "https://s3.climb.ac.uk"
          source_dir: "glacier.tar"
          destination_dir: "glacier-ubuntu_22.04-nextflow_25.10.3.tar"
